### ISSUE TITLE
Bidirectional Mirroring - Where does the code go?

### ISSUE THREAD

**Issue by arunk** [shyguy1412/bb-external-editor#1]
The section of the README.md titled Bidirectional Mirroring, has some code about creating a context and then watching. Where exactly does this code go? Does it need to go in a script? Or in a config file?

**Comment by shyguy1412** [comment]
It goes into the `build.mjs` file

**Comment by arunk** [comment]
Thanks for your help. Sorry one other question related to this. Is there a way of specifying a remote path and local path not to mirror?

**Comment by shyguy1412** [comment]
No, there is not. The base features are fairly simple and opinionated to my tastes (since they where mainly developed for me initially).

You can however create custom plugin extensions to achieve the exact behavior you are looking for.
