### ISSUE TITLE
Compilation has suddenly stopped working. Changes in servers/home/file.js not reflected in build/home/file.js

### ISSUE THREAD

**Issue by arunk** [shyguy1412/bb-external-editor#3]
So this was suddenly driving me crazy, I was making changes to a script in my servers/home/ folder in bb-external-editor, but the changes were not being reflected in the game. So I checked the connection, and made small changes but nothing happened. Then I checked the build/home folder and I discovered that even that file wasn't reflecting the changes to the file in the servers/home folder. So I thought maybe there was a glitch and I deleted the build folder, but when I ran `$ npm start` and checked the build folder, the script file was reflecting the old script! It hadn't updated it to the new script file. I tried removing a couple of changes I made to build.mjs, where I tried to use JSX, I removed all those changes and it is still not working. This is not making any sense at all, it feels like it is reading from some cache, but I don't even know where it has cached the scripts.

Here is my build.mjs:
import { context } from 'esbuild';
import { BitburnerPlugin } from 'esbuild-bitburner-plugin';

const createContext = async () => await context({
  entryPoints: [
    'servers/**/*.js',
    'servers/**/*.jsx',
    'servers/**/*.ts',
    'servers/**/*.tsx',
  ],
  outbase: "./servers",
  outdir: "./build",
  plugins: [
    BitburnerPlugin({
      port: 12525,
      types: 'NetscriptDefinitions.d.ts',
      mirror: {
      },
      distribute: {
      },
      extensions: [ ],
      pushOnConnect: true,
    })
  ],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  logLevel: 'debug',
});

const ctx = await createContext();
ctx.watch();

My servers/home/augCost.js:
import { formatMoney, getConfiguration } from './utils/helpers.js';

const hackingStats = [
    'hacking_chance',
    'hacking_speed',
    'hacking_money',
    'hacking_grow',
    'hacking',
    'hacking_exp'
];

const combatStats = [
    'strength',
    'strength_exp',
    'defense',
    'defense_exp',
    'dexterity',
    'dexterity_exp',
    'agility',
    'agility_exp'
];

const charismaStats = [
    'charisma',
    'charisma_exp'
];

const hacknetStats = [
    'hacknet_node_money',
    'hacknet_node_purchase_cost',
    'hacknet_node_ram_cost',
    'hacknet_node_core_cost',
    'hacknet_node_level_cost'
];

const repStats = [
    'company_rep',
    'faction_rep'
];

const workStats = [
    'work_money'
];

const crimeStats = [
    'crime_success',
    'crime_money'
];

const bladeBurnerStats = [
    'bladeburner_max_stamina',
    'bladeburner_stamina_gain',
    'bladeburner_analysis',
    'bladeburner_success_chance'
];

const argsSchema = [
    [ 'hacking', false ],
    [ 'combat', false ],
    [ 'charisma', false ],
    [ 'hacknet', false ],
    [ 'rep', false ],
    [ 'work', false ],
    [ 'crime', false ],
    [ 'bladeburner', false ]
];

export async function main(ns) {
    const ownedAugs = ns.singularity.getOwnedAugmentations();

    let augsAvailable = [];
    for (const faction of ns.getPlayer().factions) {
        for (const aug of ns.singularity.getAugmentationsFromFaction(faction)) {
            const stats = ns.singularity.getAugmentationStats(aug);
            for (const stat in stats) {
                ns.tprint(`${stat}: ${stats[stat]}`);
            }
            return;
        }
    }
}

function autocomplete(data, _) {
    data.flags(argsSchema);
    return [];
}

And build/home/augCost.js:
// servers/home/augCost.js
async function main(ns) {
  const ownedAugs = ns.singularity.getOwnedAugmentations();
  let augsAvailable = [];
  for (const faction of ns.getPlayer().factions) {
    for (const aug of ns.singularity.getAugmentationsFromFaction(faction)) {
      const stats = ns.singularity.getAugmentationStats(aug);
      for (const stat in stats) {
        ns.tprint(`${stat}: ${stats[stat]}`);
      }
      return;
    }
  }
}
export {
  main
};

**Comment by shyguy1412** [comment]
what does the console output say?

**Comment by arunk** [comment]
Console running `$ npm start` says 12 warnings, [watch] build finished. The warnings are about the use of eval in some of the scripts I have.

**Comment by arunk** [comment]
Also I should have checked, but build is working for other files. Just not for this file augCost.js. That is other files are getting compiled when I make a change in them, and the changes are reflected in build/home, and also distributed to the BB game. But the build seems to silently fail for just this augCost.js file. Ok further investigation, it seems like if I add a ns.tprint statement to the main function then it updates. But for some reason it is only the autocomplete function that is not being exported to the build/home js file. It is only this one function that for some reason is missing. But it works in other files, I have other scripts that use autcomplete and they get exported fine.

**Comment by arunk** [comment]
Yes that was the issue. Thanks! I'm closing this issue.
